"""
dag_sample
DAG file auto-generated by AstroBuild.
"""
import os
import time
from datetime import datetime

import pandas as pd
from airflow.decorators import dag, task
from airflow.models import Variable
from airflow.utils import timezone
from airflow.utils.dates import days_ago
from astro import sql as aql
from astro.files import File
from astro.sql.table import Table

os.environ["AIRFLOW__CORE__XCOM_BACKEND"] = ""

@aql.dataframe()
def task_1_func():
    return "hello world"

@aql.transform(conn_id='ambassadors')
def task_2_func():
    return """
    select 1 as hello_world;"""

@dag(schedule_interval='0 0 * * *', start_date=datetime(2022, 7, 29, 22, 16, 18), catchup=False, tags=[])
def dag_sample():
    task_1 = task_1_func()
    task_2 = task_2_func(output_table=Table(conn_id='ambassadors', name='tmp_astro_dag_sample_task_2'))

dag_obj = dag_sample()